name: Build

on:
  pull_request:
    paths: ['HemaDungeon/**']
  workflow_call:

jobs:
  web_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: build
        run: |
          cd HemaDungeon
          dotnet publish -c Release -r linux-x64 --self-contained
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          retention-days: 1
          path: |
            HemaDungeon/bin/Release/net8.0/linux-x64/publish/*