name: Deploy NetApi

on:
  push:
#   branches: ['master']
#    paths: ['HemaDungeon/**']

jobs:
  web_build:
    uses: ./.github/workflows/build.yaml
  web_publish:
    runs-on: ubuntu-latest
    needs: [web_build]
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
      - name: Install 7Zip
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: p7zip-rar p7zip-full
          version: 1.0
      - name: Archive to zip
        run: |
          7z a web-build.zip *
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/workflows/client.ovpn'
          SECRET: ${{ secrets.OVPN_PASSWORD }}
          TLS_KEY: ${{ secrets.OVPN_TLS_AUTH_KEY }}
        env:
          CA_CRT: ${{ secrets.OVPN_CA_CRT}}
          USER_CRT: ${{ secrets.OVPN_CLIENT_CRT }}
          USER_KEY: ${{ secrets.OVPN_CLIENT_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Copy artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USERNAME }}
          password: ${{ secrets.LOCAL_PASSWORD }}
          port: 22
          source: 'web-build.zip'
          target: '/root'
      - name: Disable Web
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USERNAME }}
          password: ${{ secrets.LOCAL_PASSWORD }}
          port: 22
          script: |
            systemctl status hema
            systemctl stop hema
      - name: Replace and start Web
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USERNAME }}
          password: ${{ secrets.LOCAL_PASSWORD }}
          port: 22
          script: |
            cd /home/orangepi
            mkdir wwwroot
            cp -r hema/wwwroot/* wwwroot/
            cp hema/appsettings.Production.json appsettings.Production.json
            rm -rf /home/orangepi/hema/*
            7z x -ohema web-build.zip
            chmod 777 hema/HemaDungeon
            rm web-build.zip
            rm -rf wwwroot/assets
            rm -rf wwwroot/index.html
            rm -rf wwwroot/vite.svg
            cp appsettings.Production.json hema/appsettings.Production.json
            cp wwwroot/* hema/wwwroot/
            rm appsettings.Production.json
            rm -rf wwwroot
            systemctl start hema
            systemctl status hema