name: Deployment
run-name: Deployment
on:
  push:
    branches: ['master']
    paths: ['HemaDungeon/**','HemaDungeon.Calculator/**']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/badnickname/hema-dungeon/hema-dungeon:1.0
          platforms: linux/arm64
          push: true
      - name: Deploy
        run: |
          sudo apt-get install -y jq curl
          ./deploy.sh ${{ secrets.PORTAINER_HTTPS }} ${{ secrets.PORTAINER_USERNAME }} ${{ secrets.PORTAINER_PASSWORD }} ${{ secrets.PORTAINER_STACK }} ${{ secrets.PORTAINER_ENDPOINT }}